language: python

sudo: false

python:
 - "3.8"

before_install:
  -   sudo apt-get update
  -   sudo apt-get install python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
          libsdl2-ttf-dev libportmidi-dev libjpeg-dev

# python-numpy xfonts-base xfonts-100dpi xfonts-75dpi xfonts-cyrillic
# libsdl-ttf2.0-dev fluid-soundfont-gm 
# libtiff5-dev musescore-soundfont-gm \
# libx11-6 
#          \
#          libx11-dev  \ 
# libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

install: 
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install isort
    - pip install pycodestyle

script: 
   - isort -c -rc
   - pycodestyle farmlib/ pygameui/ test/ *.py*
   - coverage run -m unittest

after_success:
- coverage report -m
- coveralls

