language: python

sudo: false

python:
 - "3.8"

before_install:
  -   sudo apt-get update
  -   sudo apt-get install python-dev libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev
  -   sudo apt-get install libsdl-ttf2.0-dev libportmidi-dev libjpeg-dev

env:
  global:
    - SDL_VIDEODRIVER=dummy
    - SDL_AUDIODRIVER=disk

install: 
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install isort
    - pip install pycodestyle

script: 
   - isort -c -rc
   - pycodestyle farmlib/ pygameui/ tests/ *.py*
   - coverage run --source farmlib setup.py test

after_success:
- coverage report -m
- coveralls

