language: python

sudo: false

python:
 - "3.8"

install: 
    - pip install -r requirements.txt
    - pip install coveralls

script: 
   - isort -c -rc
   - coverage run -m unittest

after_success:
- coveralls

